services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  
  api_gateway:
    build:
      context: ./services/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - qdrant

  file_processor:
    build:
      context: ./services/file_processor
    ports:
      - "8001:8001"
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - qdrant

  agent:
    build:
      context: ./services/agent
    ports:
      - "8003:8003"
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - qdrant
  
  worker:
    build:
      context: ./services/worker
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - qdrant
  

volumes:
  qdrant_data:
